server:
  port: 8001

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #springboot 2.6.x???Swagger??????

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-wait: 10s
        max-idle: 8
        min-idle: 1
    timeout: PT1H
    password: